import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "@shared/providers";
import { Navigation } from "@shared/widgets/Navigation.widget";
import { Footer } from "@shared/widgets/Footer.widget";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru" suppressHydrationWarning>
			<body
			// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AppProviders>
					<div className="flex justify-center items-center w-full">
						<Navigation />
					</div>

					{children}

					<Footer />
				</AppProviders>
			</body>
		</html>
	);
}
